version: '2'

services:
  web:
    image: ${DOCKER_IMAGE}
    container_name: web
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/test-db
    command: yarn test:integration

  mongo:
    image: mongo:3.4.10-jessie
    ports:
      - "27017:27017"
