version: '3'

services:
  test:
    image: ${DOCKER_IMAGE}
    container_name: test
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/test-db
    command: yarn test:integration

  mongo:
    image: circleci/mongo
    expose:
      - "27017"
