---
- name: Create working directory
  file:
    path: "{{ working_directory }}"
    state: directory

- name: Stop system nginx service
  service:
    name: nginx
    state: stopped
  ignore_errors: yes

- name: Copy nginx configuration
  copy:
    src: "{{ nginx_path }}"
    dest: "{{ working_directory }}/nginx.conf"
  register: nginx_conf

- name: Login to Docker Hub
  shell: docker login -u {{ DOCKER_USER }} -p {{ DOCKER_PASSWORD }}

- name: Pull backend Docker Hub image
  shell: docker pull {{ docker_image }}

- name: Copy frontend build folder
  copy:
    src: "{{ circleci_working_directory }}/frontend/build/"
    dest: "{{ working_directory }}/build/"

- name: Copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ working_directory }}/docker-compose.yml"

- name: Start server containers
  shell: docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ working_directory }}"

- name: Restart docker nginx
  shell: docker restart nginx
  when: nginx_conf.changed

- name: Remove dangling images
  shell: docker rmi $(docker images -qa -f "dangling=true")
  ignore_errors: yes