---
  - name: Update software
    apt:
      update_cache: yes
      upgrade: yes

  - name: Ensure hostname set
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Generate /etc/hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts